### ISSUE TITLE
Couldn't find libgrvrf.so on Pixel Daydream

### ISSUE THREAD

**Issue by felislynx-silae** [Samsung/GearVRf#1045]
My app is correctly running on GearVR so after i obtained Pixel i've tried to run it (after adding backend_daydream) on daydream. Since there is no such wiki/tutorial how to setup project for daydream i don't know if it's a issue with lib or my setup. Here is logcat error:
02-15 19:53:15.588 23156-23163/? E/art: Failed sending reply to debugger: Broken pipe
02-15 19:53:15.697 23156-23156/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: pl.lynx.daydream.test, PID: 23156
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/pl.lynx.daydream.test-2/base.apk"],nativeLibraryDirectories=[/data/app/pl.lynx.daydream.test-2/lib/arm64, /system/fake-libs64, /data/app/pl.lynx.daydream.test-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libgvrf.so"
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                       at java.lang.System.loadLibrary(System.java:1530)
                                                       at org.gearvrf.GVRActivity.<clinit>(GVRActivity.java:61)
                                                       at java.lang.Class.newInstance(Native Method)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by liaxim** [comment]
Daydream has 64bit binaries but we do not. In your app's gradle file you need to add this:

```
android {

    // ignore the x86 and arm-v8 files from the google vr libraries
    packagingOptions {
        exclude 'lib/x86/libgvr.so'
        exclude 'lib/arm64-v8a/libgvr.so'
        if (!rootProject.hasProperty("ARM64")) {
            exclude 'lib/arm64-v8a/*.so'
        }
    }
}
```

**Comment by felislynx-silae** [comment]
Yup, it's working like a charm. Maybe rendering is little different but it's working. Thanks :) Issue is ready to be closed (but i think your answer should go to WIKI page) cheers

**Comment by liaxim** [comment]
@felislynx-silae It is too late for your case but we will add a template project that will help starting apps from scratch: https://github.com/gearvrf/GearVRf-Demos/pull/403. Or at least serve as a reference.

**Comment by felislynx-silae** [comment]
@liaxim IT's good to know. Also it might be interesting that if i put <category android:name="com.google.intent.category.DAYDREAM" /> into intent filter in manifest, app is black after i open it in daydream :) Without this category, it's working fine but it's not in daydream lobby

**Comment by liaxim** [comment]
@felislynx-silae Are you referring to ``<intent-filter> <action android:name="android.intent.action.MAIN" /> <category android:name="com.google.intent.category.DAYDREAM" /> </intent-filter>``? Any chance you could share with us the activity section of your AndroidManifest.xml? Thanks.

**Comment by felislynx-silae** [comment]
Sure:
 <activity
            android:name=".ui.activities.ApplicationActivity"
            android:configChanges="screenSize|orientation|keyboardHidden|keyboard"
            android:excludeFromRecents="true"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:screenOrientation="landscape"
            android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.INFO" /> 
                <category android:name="com.google.intent.category.DAYDREAM" /> 
            </intent-filter>

        </activity>
            
        <meta-data
            android:name="com.samsung.android.vr.application.mode"
            android:value="vr_only" />
