### ISSUE TITLE
Bug in build: dlopen failed: cannot locate symbol "vrapi_GetInputDeviceCapabilities"

### ISSUE THREAD

**Issue by felislynx-silae** [Samsung/GearVRf#1117]
About an hour ago, this build was running perfectly. Now it's throwing this error. I'm on 3.1.2-SNAPSHOT.
I've got bunch of updates on SGS6 before it stopped working.
```
03-31 11:25:37.752 16653-16653/eu.lynxit.sampleapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: eu.lynxit.sampleapp, PID: 16653
                                                                     java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "vrapi_GetInputDeviceCapabilities" referenced by "/data/app/eu.lynxit.sampleapp-1/lib/arm/libgvrf-oculus.so"...
                                                                         at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                                                                         at java.lang.System.loadLibrary(System.java:1530)
                                                                         at org.gearvrf.OvrActivityNative.<clinit>(OvrActivityNative.java:24)
                                                                         at org.gearvrf.OvrActivityDelegate.onCreate(OvrActivityDelegate.java:36)
                                                                         at org.gearvrf.GVRActivity.onCreate(GVRActivity.java:102)
                                                                         at eu.lynxit.sampleapp.MainActivity.onCreate(MainActivity.java:12)
                                                                         at android.app.Activity.performCreate(Activity.java:6912)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
                                                                         at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by liaxim** [comment]
Hi,

Could you unzip your apk, go to ./lib/armeabi-v7a/, run these commands and let us know the output?

---

-  ``file libvrapi.so``

This is what I expect the output to be:
```
libvrapi.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=c8ac9d845c94215c2ca68df0f288aebad384f74c, stripped
```

---

-  ``readelf -s libvrapi.so``

This is what I expect the output to be:
```
Symbol table '.dynsym' contains 99 entries:
   Num:    Value  Size Type    Bind   Vis      Ndx Name
     0: 00000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_finalize@LIBC (2)
     2: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_atexit@LIBC (2)
     3: 0000193c  4980 FUNC    GLOBAL DEFAULT   12 vrapi_Initialize
     4: 00000000     0 FUNC    GLOBAL DEFAULT  UND __android_log_print
     5: 00000000     0 OBJECT  GLOBAL DEFAULT  UND __stack_chk_guard@LIBC (2)
     6: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_guard_acquire
     7: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_guard_release
     8: 00000000     0 FUNC    GLOBAL DEFAULT  UND __aeabi_memclr8
     9: 00000000     0 FUNC    GLOBAL DEFAULT  UND snprintf@LIBC (2)
    10: 00000000     0 FUNC    GLOBAL DEFAULT  UND __stack_chk_fail@LIBC (2)
    11: 00000000     0 FUNC    GLOBAL DEFAULT  UND abort@LIBC (2)
    12: 00005e8c     8 FUNC    WEAK   DEFAULT   12 __aeabi_unwind_cpp_pr1
    13: 00002cb0    16 FUNC    GLOBAL DEFAULT   12 vrapi_GetVersionString
    14: 00005e84     8 FUNC    GLOBAL DEFAULT   12 __aeabi_unwind_cpp_pr0
    15: 00002cc0    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetTimeInSeconds
    16: 00002cd4    20 FUNC    GLOBAL DEFAULT   12 vrapi_Shutdown
    17: 00002ce8    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemPropertyIn
    18: 00002cfc    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemPropertyFl
    19: 00002d10    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemPropertySt
    20: 00002d24    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemStatusInt
    21: 00002d38    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemStatusFloa
    22: 00002d4c    20 FUNC    GLOBAL DEFAULT   12 vrapi_EnterVrMode
    23: 00002d60    20 FUNC    GLOBAL DEFAULT   12 vrapi_LeaveVrMode
    24: 00002d74    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetPredictedDisplay
    25: 00002d88    32 FUNC    GLOBAL DEFAULT   12 vrapi_GetPredictedTrackin
    26: 00002da8    20 FUNC    GLOBAL DEFAULT   12 vrapi_RecenterPose
    27: 00002dbc    56 FUNC    GLOBAL DEFAULT   12 vrapi_CreateTextureSwapCh
    28: 00002df4    20 FUNC    GLOBAL DEFAULT   12 vrapi_CreateTextureSwapCh
    29: 00002e08    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetTextureSwapChain
    30: 00002e1c    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetTextureSwapChain
    31: 00002e30    20 FUNC    GLOBAL DEFAULT   12 vrapi_SetTextureSwapChain
    32: 00002e44    20 FUNC    GLOBAL DEFAULT   12 vrapi_DestroyTextureSwapC
    33: 00002e58    20 FUNC    GLOBAL DEFAULT   12 vrapi_SubmitFrame
    34: 00002e6c    20 FUNC    GLOBAL DEFAULT   12 vrapi_SubmitFrame2_temp
    35: 00002e80    20 FUNC    GLOBAL DEFAULT   12 ovr_GetLocalPreferenceVal
    36: 00002e94    20 FUNC    GLOBAL DEFAULT   12 ovr_SetLocalPreferenceVal
    37: 00002ea8    20 FUNC    GLOBAL DEFAULT   12 vrapi_EnumerateInputDevic
    38: 00002ebc    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetInputDeviceCapab
    39: 00002ed0    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetCurrentInputStat
    40: 00002ee4    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetInputTrackingSta
    41: 00002ef8    20 FUNC    GLOBAL DEFAULT   12 vrapi_RecenterInputPose
    42: 00002f0c    20 FUNC    GLOBAL DEFAULT   12 vrapi_SetRemoteEmulation
    43: 00002f20    20 FUNC    GLOBAL DEFAULT   12 vrapi_SetPropertyInt
    44: 00002f34    16 FUNC    GLOBAL DEFAULT   12 vrapi_SetPropertyFloat
    45: 00002f44    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetPropertyInt
    46: 00002f58    20 FUNC    GLOBAL DEFAULT   12 vrapi_ShowSystemUI
    47: 00002f6c    20 FUNC    GLOBAL DEFAULT   12 vrapi_ShowSystemUIWithExt
    48: 00002f80    20 FUNC    GLOBAL DEFAULT   12 vrapi_ReturnToHome
    49: 00002f94    20 FUNC    GLOBAL DEFAULT   12 vrapi_ShowFatalError
    50: 00000000     0 FUNC    GLOBAL DEFAULT  UND memcpy@LIBC (2)
    51: 00000000     0 FUNC    GLOBAL DEFAULT  UND __android_log_vprint
    52: 00005e94     8 FUNC    WEAK   DEFAULT   12 __aeabi_unwind_cpp_pr2
    53: 00000000     0 FUNC    WEAK   DEFAULT  UND __gnu_Unwind_Find_exidx
    54: 0000622c     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_VFP_
    55: 0000621c     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_VFP
    56: 0000623c     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_VFP_
    57: 0000624c     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_WMMX
    58: 000062d4     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_WMMX
    59: 00006208    20 FUNC    GLOBAL DEFAULT   12 restore_core_regs
    60: 00005748     8 FUNC    GLOBAL DEFAULT   12 _Unwind_GetCFA
    61: 00005750   164 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_RaiseExcepti
    62: 000057f4    28 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_ForcedUnwind
    63: 00005810   116 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Resume
    64: 00005884    32 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Resume_or_Re
    65: 000058a4     4 FUNC    GLOBAL DEFAULT   12 _Unwind_Complete
    66: 000058a8    24 FUNC    GLOBAL DEFAULT   12 _Unwind_DeleteException
    67: 000058c0    92 FUNC    GLOBAL DEFAULT   12 _Unwind_VRS_Get
    68: 00005944    92 FUNC    GLOBAL DEFAULT   12 _Unwind_VRS_Set
    69: 000059cc   200 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Backtrace
    70: 00000000     0 NOTYPE  WEAK   DEFAULT  UND __cxa_begin_cleanup
    71: 00000000     0 NOTYPE  WEAK   DEFAULT  UND __cxa_type_match
    72: 0000643c   904 FUNC    GLOBAL DEFAULT   12 __gnu_unwind_execute
    73: 00000000     0 NOTYPE  WEAK   DEFAULT  UND __cxa_call_unexpected
    74: 00005e9c   876 FUNC    GLOBAL DEFAULT   12 _Unwind_VRS_Pop
    75: 00006234     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_VFP_D
    76: 00006224     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_VFP
    77: 00006244     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_VFP_D_1
    78: 00006290     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_WMMXD
    79: 000062e8     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_WMMXC
    80: 00006208    20 FUNC    GLOBAL DEFAULT   12 __restore_core_regs
    81: 000062fc    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_RaiseException
    82: 000062fc    36 FUNC    GLOBAL DEFAULT   12 _Unwind_RaiseException
    83: 00006320    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_Resume
    84: 00006320    36 FUNC    GLOBAL DEFAULT   12 _Unwind_Resume
    85: 00006344    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_Resume_or_Rethr
    86: 00006344    36 FUNC    GLOBAL DEFAULT   12 _Unwind_Resume_or_Rethrow
    87: 00006368    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_ForcedUnwind
    88: 00006368    36 FUNC    GLOBAL DEFAULT   12 _Unwind_ForcedUnwind
    89: 0000638c    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_Backtrace
    90: 0000638c    36 FUNC    GLOBAL DEFAULT   12 _Unwind_Backtrace
    91: 000067c4    64 FUNC    GLOBAL DEFAULT   12 __gnu_unwind_frame
    92: 00006804    16 FUNC    GLOBAL DEFAULT   12 _Unwind_GetRegionStart
    93: 00006814    28 FUNC    GLOBAL DEFAULT   12 _Unwind_GetLanguageSpecif
    94: 00006830     8 FUNC    GLOBAL DEFAULT   12 _Unwind_GetDataRelBase
    95: 00006838     8 FUNC    GLOBAL DEFAULT   12 _Unwind_GetTextRelBase
    96: 000090b0     0 NOTYPE  GLOBAL DEFAULT  ABS _edata
    97: 000090b0     0 NOTYPE  GLOBAL DEFAULT  ABS __bss_start
    98: 00009120     0 NOTYPE  GLOBAL DEFAULT  ABS _end
```

**Comment by felislynx-silae** [comment]
@liaxim Could you provide commands that are running on Windows? I'll try to revive my ubuntu laptop.

**Comment by liaxim** [comment]
If you are ok with it, you could just send the libvrapi.so from your apk. This is a library from the Oculus Mobile SDK. I'd like to find out what version exactly you are using. Should be 1.5.0 but from the sound of the error you get, I don't know what to think.

**Comment by felislynx-silae** [comment]
Funny part. It was running perfectly (this project which was created to recreate ConcurentModificationException) in morning because i was testing it on 3 devices. Same as my main project. Around 11pm this happened (as far as i can tell, there were updates on all devices regarding oculus software)
```
file libvrapi.so
libvrapi.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=9f5348b093be1a129a05d073630253220e299edc, stripped
```
```
readelf -s libvrapi.so

Symbol table '.dynsym' contains 91 entries:
   Num:    Value  Size Type    Bind   Vis      Ndx Name
     0: 00000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_finalize@LIBC (2)
     2: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_atexit@LIBC (2)
     3: 00001704  4652 FUNC    GLOBAL DEFAULT   12 vrapi_Initialize
     4: 00000000     0 FUNC    GLOBAL DEFAULT  UND __android_log_print
     5: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_guard_acquire
     6: 00000000     0 FUNC    GLOBAL DEFAULT  UND __cxa_guard_release
     7: 00000000     0 FUNC    GLOBAL DEFAULT  UND __aeabi_memclr8
     8: 00000000     0 FUNC    GLOBAL DEFAULT  UND snprintf@LIBC (2)
     9: 00000000     0 FUNC    GLOBAL DEFAULT  UND __stack_chk_fail@LIBC (2)
    10: 00000000     0 FUNC    GLOBAL DEFAULT  UND abort@LIBC (2)
    11: 00000000     0 OBJECT  GLOBAL DEFAULT  UND __stack_chk_guard@LIBC (2)
    12: 00005890     8 FUNC    WEAK   DEFAULT   12 __aeabi_unwind_cpp_pr1
    13: 00002930    16 FUNC    GLOBAL DEFAULT   12 vrapi_GetVersionString
    14: 00005888     8 FUNC    GLOBAL DEFAULT   12 __aeabi_unwind_cpp_pr0
    15: 00002940    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetTimeInSeconds
    16: 00002954    20 FUNC    GLOBAL DEFAULT   12 vrapi_Shutdown
    17: 00002968    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemPropertyIn
    18: 0000297c    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemPropertyFl
    19: 00002990    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemPropertySt
    20: 000029a4    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemStatusInt
    21: 000029b8    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetSystemStatusFloa
    22: 000029cc    20 FUNC    GLOBAL DEFAULT   12 vrapi_EnterVrMode
    23: 000029e0    20 FUNC    GLOBAL DEFAULT   12 vrapi_LeaveVrMode
    24: 000029f4    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetPredictedDisplay
    25: 00002a08    32 FUNC    GLOBAL DEFAULT   12 vrapi_GetPredictedTrackin
    26: 00002a28    20 FUNC    GLOBAL DEFAULT   12 vrapi_RecenterPose
    27: 00002a3c    56 FUNC    GLOBAL DEFAULT   12 vrapi_CreateTextureSwapCh
    28: 00002a74    20 FUNC    GLOBAL DEFAULT   12 vrapi_CreateTextureSwapCh
    29: 00002a88    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetTextureSwapChain
    30: 00002a9c    20 FUNC    GLOBAL DEFAULT   12 vrapi_GetTextureSwapChain
    31: 00002ab0    20 FUNC    GLOBAL DEFAULT   12 vrapi_SetTextureSwapChain
    32: 00002ac4    20 FUNC    GLOBAL DEFAULT   12 vrapi_DestroyTextureSwapC
    33: 00002ad8    20 FUNC    GLOBAL DEFAULT   12 vrapi_SubmitFrame
    34: 00002aec    20 FUNC    GLOBAL DEFAULT   12 ovr_GetLocalPreferenceVal
    35: 00002b00    20 FUNC    GLOBAL DEFAULT   12 ovr_SetLocalPreferenceVal
    36: 00002b14    20 FUNC    GLOBAL DEFAULT   12 vrapi_SetPropertyInt
    37: 00000000     0 FUNC    GLOBAL DEFAULT  UND memcpy@LIBC (2)
    38: 00002b28    20 FUNC    GLOBAL DEFAULT   12 vrapi_SetPropertyFloat
    39: 00002b3c    20 FUNC    GLOBAL DEFAULT   12 vrapi_ShowSystemUI
    40: 00002b50    20 FUNC    GLOBAL DEFAULT   12 vrapi_ShowSystemUIWithExt
    41: 00002b64    20 FUNC    GLOBAL DEFAULT   12 vrapi_ReturnToHome
    42: 00002b78    20 FUNC    GLOBAL DEFAULT   12 vrapi_ShowFatalError
    43: 00000000     0 FUNC    GLOBAL DEFAULT  UND __android_log_vprint
    44: 00005898     8 FUNC    WEAK   DEFAULT   12 __aeabi_unwind_cpp_pr2
    45: 00000000     0 FUNC    WEAK   DEFAULT  UND __gnu_Unwind_Find_exidx
    46: 00005c30     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_VFP_
    47: 00005c20     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_VFP
    48: 00005c40     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_VFP_
    49: 00005c50     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_WMMX
    50: 00005cd8     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Restore_WMMX
    51: 00005c0c    20 FUNC    GLOBAL DEFAULT   12 restore_core_regs
    52: 0000514c     8 FUNC    GLOBAL DEFAULT   12 _Unwind_GetCFA
    53: 00005154   164 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_RaiseExcepti
    54: 000051f8    28 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_ForcedUnwind
    55: 00005214   116 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Resume
    56: 00005288    32 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Resume_or_Re
    57: 000052a8     4 FUNC    GLOBAL DEFAULT   12 _Unwind_Complete
    58: 000052ac    24 FUNC    GLOBAL DEFAULT   12 _Unwind_DeleteException
    59: 000052c4    92 FUNC    GLOBAL DEFAULT   12 _Unwind_VRS_Get
    60: 00005348    92 FUNC    GLOBAL DEFAULT   12 _Unwind_VRS_Set
    61: 000053d0   200 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Backtrace
    62: 00000000     0 NOTYPE  WEAK   DEFAULT  UND __cxa_begin_cleanup
    63: 00000000     0 NOTYPE  WEAK   DEFAULT  UND __cxa_type_match
    64: 00005e40   904 FUNC    GLOBAL DEFAULT   12 __gnu_unwind_execute
    65: 00000000     0 NOTYPE  WEAK   DEFAULT  UND __cxa_call_unexpected
    66: 000058a0   876 FUNC    GLOBAL DEFAULT   12 _Unwind_VRS_Pop
    67: 00005c38     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_VFP_D
    68: 00005c28     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_VFP
    69: 00005c48     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_VFP_D_1
    70: 00005c94     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_WMMXD
    71: 00005cec     0 FUNC    GLOBAL DEFAULT   12 __gnu_Unwind_Save_WMMXC
    72: 00005c0c    20 FUNC    GLOBAL DEFAULT   12 __restore_core_regs
    73: 00005d00    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_RaiseException
    74: 00005d00    36 FUNC    GLOBAL DEFAULT   12 _Unwind_RaiseException
    75: 00005d24    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_Resume
    76: 00005d24    36 FUNC    GLOBAL DEFAULT   12 _Unwind_Resume
    77: 00005d48    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_Resume_or_Rethr
    78: 00005d48    36 FUNC    GLOBAL DEFAULT   12 _Unwind_Resume_or_Rethrow
    79: 00005d6c    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_ForcedUnwind
    80: 00005d6c    36 FUNC    GLOBAL DEFAULT   12 _Unwind_ForcedUnwind
    81: 00005d90    36 FUNC    GLOBAL DEFAULT   12 ___Unwind_Backtrace
    82: 00005d90    36 FUNC    GLOBAL DEFAULT   12 _Unwind_Backtrace
    83: 000061c8    64 FUNC    GLOBAL DEFAULT   12 __gnu_unwind_frame
    84: 00006208    16 FUNC    GLOBAL DEFAULT   12 _Unwind_GetRegionStart
    85: 00006218    28 FUNC    GLOBAL DEFAULT   12 _Unwind_GetLanguageSpecif
    86: 00006234     8 FUNC    GLOBAL DEFAULT   12 _Unwind_GetDataRelBase
    87: 0000623c     8 FUNC    GLOBAL DEFAULT   12 _Unwind_GetTextRelBase
    88: 00009090     0 NOTYPE  GLOBAL DEFAULT  ABS _edata
    89: 00009090     0 NOTYPE  GLOBAL DEFAULT  ABS __bss_start
    90: 00009100     0 NOTYPE  GLOBAL DEFAULT  ABS _end
```

**Comment by liaxim** [comment]
It is the file from the 1.0.4 sdk. Can you please rebuild your app with gradle and passing the ``--refresh-dependencies`` argument?

```gradlew --refresh-dependencies clean installDebug```

**Comment by felislynx-silae** [comment]
@liaxim same result.
Also made "clean project". All files you might want to see are in https://github.com/felislynx-silae/GearBugSample

**Comment by liaxim** [comment]
You have ./app/src/main/jniLibs/armeabi-v7a/libvrapi.so in your git repo. Please remove this file. The correct libvrapi.so is included in the oculus backend aar.

**Comment by felislynx-silae** [comment]
@liaxim That was it. This part was in my project for 7 months. Good to know that i can delete it. Thank you very much :)
