### ISSUE TITLE
S8: libgdx plugin problem with gvr-modelviewer2&gvr-widgetviewer

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#1139]
The app just freezes at the logo or even prior to that. Almost certainly it is down to the widget plugin extension. Works on Note 5. The plugin has some dodgy mechanics that can be highly sensitive to timing.

Doesn't work with Oculus and Daydream.

**Comment by liaxim** [comment]
Unsurprisingly gvr-widgetviewer doesn't work either. I assume we will want this fixed for the release and will be looking into it.

**Comment by liaxim** [comment]
Still working on it. Had trouble deciphering which thread needs to wait on what. Clearly something is deadlocking.

**Comment by liaxim** [comment]
After getting the widget plugin working there is this exception in gvr-modelviewer2:

```
04-12 12:57:10.211 10725 10725 E AndroidRuntime: FATAL EXCEPTION: main
04-12 12:57:10.211 10725 10725 E AndroidRuntime: Process: org.gearvrf.modelviewer2, PID: 10725
04-12 12:57:10.211 10725 10725 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'org.gearvrf.GVRSceneObject org.gearvrf.modelviewer2.Model.getModel(org.gearvrf.GVRContext)' on a null object reference
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at org.gearvrf.modelviewer2.Controller.onScrollOverModel(Controller.java:590)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at org.gearvrf.modelviewer2.ModelViewer2Manager.onScroll(ModelViewer2Manager.java:306)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at org.gearvrf.modelviewer2.ModelViewer2Activity.onScroll(ModelViewer2Activity.java:79)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at org.gearvrf.util.VRTouchPadGestureDetector.onScroll(VRTouchPadGestureDetector.java:227)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:622)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at org.gearvrf.util.VRTouchPadGestureDetector.onTouchEvent(VRTouchPadGestureDetector.java:252)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at org.gearvrf.modelviewer2.ModelViewer2Activity.dispatchTouchEvent(ModelViewer2Activity.java:85)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:545)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:11004)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5152)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5004)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4529)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4582)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4548)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4681)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4556)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4738)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4529)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4582)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4548)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4556)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4529)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7050)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6975)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6936)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7160)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7124)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7187)
04-12 12:57:10.211 10725 10725 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
```

Will look at it after I am done with the deadlock.

**Comment by thomasflynn** [comment]
#1146 was merged, can this be closed?

**Comment by liaxim** [comment]
Merged the NPE fix for gvr-modelviewer2.
