### ISSUE TITLE
Intermittent pointerIndex out of range exception while implementing similar gvr-events app 

### ISSUE THREAD

**Issue by channae** [Samsung/GearVRf#1431]
My application throws following pointerIndex out of range exception intermittently while viewing layout scene. I followed the instructions as "gvr-events" sample. Following is the only change I made.

```
    private static final float QUAD_X = 1.5f;
    private static final float QUAD_Y = 1.0f;
    private static final float HALF_QUAD_X = QUAD_X / 2.0f;
    private static final float HALF_QUAD_Y = QUAD_Y / 2.0f;
```
So far I noticed this issue while using developer mode. 

```
09-04 12:10:52.210 26256-26256/com.xxxxx.xxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.xxxxx.xxx, PID: 26256
                                                                     java.lang.IllegalArgumentException: pointerIndex out of range
                                                                         at android.view.MotionEvent.nativeGetPointerId(Native Method)
                                                                         at android.view.MotionEvent.getPointerId(MotionEvent.java:2327)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2581)
                                                                         at : com.xxxxx.xxx.EmailActivity$1.handleMessage(EmailActivity.java:84)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

Below is the code block which throws the IllegalArgumentException,

```
        mainThreadHandler = new Handler(activity.getMainLooper()) {
            @Override
            public void handleMessage(Message msg) {
                // dispatch motion event

                if (msg.what == MOTION_EVENT) {
                    MotionEvent motionEvent = (MotionEvent) msg.obj;
                    frameLayout.dispatchTouchEvent(motionEvent);
                    frameLayout.invalidate();
                    motionEvent.recycle();
                }

                if (msg.what == KEY_EVENT) {
                    int keyCode = msg.arg1;
                    // keyTextView.setText(String.format("%s %s ", "Key Pressed!",
                    //         KeyEvent.keyCodeToString(keyCode)));
                }
            }
        };
```
Appreciate any suggestions that could be helpful to isolate the problem here. Thanks in advance.

**Comment by ragner** [comment]
Hi @channae,
which version of GVRf are you using?

Could you try the current master?

**Comment by ragner** [comment]
Could you use org.gearvrf.GVRPickerInput to dispatch touch events?
Your just need add the following line:

`mPicker = new GVRPickerInput(gvrContext, mScene);`

**Comment by channae** [comment]
Hi @ragner,

My application is running on 3.1.2-SNAPSHOT. Seems like GVRPickerInput is not available in that version.

**Comment by liaxim** [comment]
@channae I updated the 3.1.2-SNAPSHOT. You will need to refresh your gradle cache to make sure you really get the latest.

**Comment by channae** [comment]
I did not encounter this issue recently. Therefore closing this issue.
