### ISSUE TITLE
GVRMesh getVertices() throws UnsupportedOperationException in 4.0

### ISSUE THREAD

**Issue by SteveGreatApe** [Samsung/GearVRf#1561]
After switching over to 4.0 i'm now getting UnsupportedOperationException when I call GVRMesh.getVertices(). The mesh is simple one created with a call GVRContext createQuad(width, height).

```
10-25 09:10:19.628 22395-22808/com.greatape.avrkbapp W/System.err: java.lang.UnsupportedOperationException
10-25 09:10:19.629 22395-22808/com.greatape.avrkbapp W/System.err:     at java.nio.FloatBuffer.array(FloatBuffer.java:511)
10-25 09:10:19.629 22395-22808/com.greatape.avrkbapp W/System.err:     at org.gearvrf.GVRMesh.getVertices(GVRMesh.java:126)
10-25 09:10:19.629 22395-22808/com.greatape.avrkbapp W/System.err:     at com.greatape.avrkeyboard.util.AvrUtil.offsetQuad(AvrUtil.java:35)
10-25 09:10:19.629 22395-22808/com.greatape.avrkbapp W/System.err:     at com.greatape.avrkeyboard.model.AvrKeyboard.createBackground(AvrKeyboard.java:463)
...
```

If anyone else with the same problem wants a workaround this function seems to work for me:

```
    public static float[] getMeshVertices(GVRMesh mesh) {
        // For 4.0 use this alternative
        GVRVertexBuffer vertexBuffer = mesh.getVertexBuffer();
        FloatBuffer floatBuffer = vertexBuffer.getFloatVec("a_position");
        int count = floatBuffer.remaining();
        float[] vertices = new float[count];
        floatBuffer.get(vertices);
        // For 3.3 this still works
//        float[] vertices = mesh.getVertices(); // Throws UnsupportedOperationException in 4.0
        return vertices;
    }

```

**Comment by liaxim** [comment]
@SteveGreatApe Thank you for letting us know. https://github.com/Samsung/GearVRf/pull/1563 fixes getVertices specifically. Also getVerticesDirect is added in case you could work with the direct FloatBuffer instead of the Java array copy.

**Comment by liaxim** [comment]
We merged the fix. Can we close the issue?

**Comment by SteveGreatApe** [comment]
Yes, working okay now, thanks.
