### ISSUE TITLE
GVRScene.removeAllSceneObjects() removes picker from scene

### ISSUE THREAD

**Issue by SteveGreatApe** [Samsung/GearVRf#1691]
I'm using GVRScene.removeAllSceneObjects() to clean up a scene of everything I've added before re-creating a new set of scene objects. I'm assuming this is supposed to be safe to use in this way and it shouldn't be removing any system objects that I didn't specifically add myself.

In the latest code it's causing a problem as it's also removing the picker pointer.

**Comment by NolaDonato** [comment]
Yeah, removeAllSceneObjects does remove ALL of the scene objects, not just the ones you added. It is intended to clear out the whole scene, including any objects added by GearVRf. 
 If you only want to remove only the objects you added, you can put all of them under a single root and then remove that root node. It will leave all of the other scene objects there and remove just the ones you added. Would that approach work for you?

**Comment by SteveGreatApe** [comment]
It was a bit lazy programming to use removeAllSceneObjects() instead of just managing my own list of what objects I've added at removing those.

If removeAllSceneObjects() is going to remove system objects that it doesn't really seem suitable to be exposed in the general purpose API unless there's some specific reason why someone might want to do remove those along with their own.

**Comment by NolaDonato** [comment]
We discussed this internally and decided to make GVRScene.removeAllSceneObjects put back the controllers, restoring the pointers also. I have committed this fix to PR #1646.What it will do is remove all the cursor controllers, then remove the scene objects and then put back the cursor controllers. It does this by calling GVRInputManager.selectController again.  Please test it and let me know if it works for your case or if it is too slow.

**Comment by SteveGreatApe** [comment]
Hi, I've tried integrating this change and hit a problem, with the Gear Controller active I called removeAllSceneObjects() and it got into a recursive call sequence and overflowed the stack.
```

01-10 11:48:41.263 14102-14735/com.greatape.avrgallery W/System.err: Caused by: java.lang.StackOverflowError: stack size 1038KB
01-10 11:48:41.263 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.GVRViewManager.registerDrawFrameListener(GVRViewManager.java:161)
01-10 11:48:41.263 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.GVRBehavior.startListening(GVRBehavior.java:126)
01-10 11:48:41.263 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.GVRBehavior.onEnable(GVRBehavior.java:78)
01-10 11:48:41.264 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.GVRComponent.setEnable(GVRComponent.java:140)
01-10 11:48:41.264 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.GVRCursorController.setEnable(GVRCursorController.java:816)
01-10 11:48:41.264 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRGazeCursorController.setEnable(GVRGazeCursorController.java:146)
.....
01-10 11:48:41.472 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager.removeCursorController(GVRInputManager.java:268)
01-10 11:48:41.472 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.GVRCursorController.setEnable(GVRCursorController.java:837)
01-10 11:48:41.472 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRGazeCursorController.setEnable(GVRGazeCursorController.java:146)
01-10 11:48:41.472 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager$SingleControllerSelector.onCursorControllerAdded(GVRInputManager.java:668)
01-10 11:48:41.473 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager.addCursorController(GVRInputManager.java:250)
01-10 11:48:41.473 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager$SingleControllerSelector.onCursorControllerRemoved(GVRInputManager.java:741)
01-10 11:48:41.473 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager.removeCursorController(GVRInputManager.java:268)
01-10 11:48:41.473 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.GVRCursorController.setEnable(GVRCursorController.java:837)
01-10 11:48:41.473 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRGazeCursorController.setEnable(GVRGazeCursorController.java:146)
01-10 11:48:41.473 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager$SingleControllerSelector.onCursorControllerAdded(GVRInputManager.java:668)
01-10 11:48:41.473 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager.addCursorController(GVRInputManager.java:250)
01-10 11:48:41.473 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager$SingleControllerSelector.onCursorControllerRemoved(GVRInputManager.java:741)
01-10 11:48:41.474 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager.removeCursorController(GVRInputManager.java:268)
01-10 11:48:41.474 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager.clear(GVRInputManager.java:380)
01-10 11:48:41.474 14102-14735/com.greatape.avrgallery W/System.err:     at org.gearvrf.GVRScene.removeAllSceneObjects(GVRScene.java:144)
01-10 11:48:41.474 14102-14735/com.greatape.avrgallery W/System.err:     at com.greatape.avrgallery.VrGalleryMain.switchToScene(VrGalleryMain.java:72)

```

**Comment by SteveGreatApe** [comment]
And another problem, when I call removeAllSceneObjects() very soon after initialising the controller with the inputManager.selectController() call, so presumably it's still sorting itself out on another thread, sometimes I hit this ConcurrentModificationException exception:
```

01-10 12:41:46.864 18683-19068/com.greatape.avrgallery W/System.err: java.util.ConcurrentModificationException
01-10 12:41:46.864 18683-19068/com.greatape.avrgallery W/System.err:     at java.util.ArrayList$Itr.next(ArrayList.java:831)
01-10 12:41:46.864 18683-19068/com.greatape.avrgallery W/System.err:     at org.gearvrf.io.GVRInputManager.clear(GVRInputManager.java:377)
01-10 12:41:46.865 18683-19068/com.greatape.avrgallery W/System.err:     at org.gearvrf.GVRScene.removeAllSceneObjects(GVRScene.java:144)
01-10 12:41:46.865 18683-19068/com.greatape.avrgallery W/System.err:     at com.greatape.avrgallery.VrGalleryMain.switchToScene(VrGalleryMain.java:72)
01-10 12:41:46.865 18683-19068/com.greatape.avrgallery W/System.err:     at com.greatape.avrgallery.VrGalleryMain.switchScene(VrGalleryMain.java:52)
01-10 12:41:46.865 18683-19068/com.greatape.avrgallery W/System.err:     at com.greatape.avrgallery.VrGalleryMain.onInit(VrGalleryMain.java:42)
01-10 12:41:46.865 18683-19068/com.greatape.avrgallery W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by NolaDonato** [comment]
I will look at this and give you a patch today. Another thread must be simultaneously accessing the controllers list. If I make this a copy on write array or do some locking it will fix the issue.

**Comment by NolaDonato** [comment]
I have fixed the two issues you mentioned. I tested by modifying gvr-controller to reset the scene. Initially I encountered both of your issues. After my patch, they appear to be fixed. Let me know if they are fixed for you as well.
