### ISSUE TITLE
Crash when detach the device from Gear when the controller is connected 

### ISSUE THREAD

**Issue by felipecs81** [Samsung/GearVRf#1777]
Hi Guys,

I am working on a project for Gear VR and I am using version 4.0.1-SNAPSHOT.
So far so good, I am able to connect the control and perform all operations, but when I disconnect the device from Gear, an exception is thrown into an internal class.
This only occurs when you have a control connected, if I am using only the headset this error does not happens. I have already tried to disable or invalidate the control on the onDestroy method of activity but nothing worked.
This also happens in this module of the GearVRDemo Project. gvr-controller
Help me, please, just need to figure this out to finish my project.

Here is the error.

Thank you very much.

03-09 12:01:32.858 22270-22358/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 8836
                                                   Process: au.com.appspeople.beingvr_android, PID: 22270
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'org.gearvrf.GVRContext org.gearvrf.io.GVRCursorController.getGVRContext()' on a null object reference
                                                       at org.gearvrf.io.GVRInputManager.addCursorController(GVRInputManager.java:272)
                                                       at org.gearvrf.io.GVRInputManager$SingleControllerSelector.onCursorControllerRemoved(GVRInputManager.java:803)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
                                                       at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:147)
                                                       at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
                                                       at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
                                                       at org.gearvrf.io.GVRInputManager.removeCursorController(GVRInputManager.java:288)
                                                       at org.gearvrf.io.GVRCursorController.setEnable(GVRCursorController.java:761)
                                                       at org.gearvrf.io.GVRGearCursorController.setEnable(GVRGearCursorController.java:244)
                                                       at org.gearvrf.io.GVRInputManager.removeCursorController(GVRInputManager.java:286)
                                                       at org.gearvrf.io.GVRGearCursorController.onDrawFrame(GVRGearCursorController.java:312)
                                                       at org.gearvrf.OvrViewManager.onDrawFrame(OvrViewManager.java:301)
                                                       at org.gearvrf.OvrVrapiActivityHandler$8.onDrawFrame(OvrVrapiActivityHandler.java:451)
                                                       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
                                                       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)

**Comment by liaxim** [comment]
@felipecs81 Thanks for letting us know. We will take a look. The snapshots are fairly recent but I updated them today just in case. Could you please retest after invalidating your gradle cache? Thanks.

**Comment by felipecs81** [comment]
Hello @liaxim 
First of all thank you for the quick return.
I created a new project just to make sure it would not have anything stored in the cache but the error keeps happening.
The initial project was to be without the controller, however, they changed their minds. The whole project had already been built using the framework 4.0.1 features.
Now I am in a very complicated situation.
I really need help in this case, maybe just put a condition there on that line so that if the context is null do nothing, just so that the exception is not thrown.

Thank you in advance.

**Comment by liaxim** [comment]
Ok, understood how to reproduce. I guess you only have a "controller" entry in your useControllerTypes. We assume there is a gaze fallback but it is not mandatory. An extra null check is all we need.

**Comment by liaxim** [comment]
@felipecs81 Fixes merged and snapshots rebuilt. Please try again.

**Comment by felipecs81** [comment]
Hi @liaxim 

Everything working perfectly.
Thank you very much for the quick solution, fantastic work.
You save my day.

**Comment by liaxim** [comment]
Awesome. Closing this issue.
