### ISSUE TITLE
App not responding and showing black screen(ANR)

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1880]
our app shows discovery screen with a count of 150 movie posters, we implemented this using recycler view and each poster is a ImageView. 
The app working fine even after loading all posters.
 
case 1: When i press back key here it will go oculus home exit dialog and if i select cancel again its navigate to my app but my discovery page showing black and some time then ANY dialog showing and ANR repeating number of times.

case 2: launch app -> Discovery screen shows -> recent windows -> kill my app -> launch app again
observe black screen and then ANR.

So there is a logic missing to clear my bitmaps while exiting app to oculus home or home screen.
in Android Recycler view will handle everything for us. So how to fix this in case of GVR.

The recyclerview i am adding to GVRViewSceneObject in my implementation.

ANR trace:
```
at java.lang.Object.wait(Native method)
  - waiting on <0x0c89a496> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:2135)
  - locked <0x0c89a496> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1021)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1328)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
  at org.gearvrf.GVRTexture.getId(GVRTexture.java:162)
  at org.gearvrf.scene_objects.GVRViewSceneObject$RootViewGroup.createRenderData(GVRViewSceneObject.java:688)
  at org.gearvrf.scene_objects.GVRViewSceneObject$RootViewGroup.onLayoutReady(GVRViewSceneObject.java:623)
  - locked <0x08c4f817> (a java.lang.Object)
  at org.gearvrf.scene_objects.GVRViewSceneObject$RootViewGroup.access$400(GVRViewSceneObject.java:495)
  at org.gearvrf.scene_objects.GVRViewSceneObject$RootViewGroup$2.onGlobalLayout(GVRViewSceneObject.java:614)
  at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1013)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2638)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1738)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7745)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
  at android.view.Choreographer.doCallbacks(Choreographer.java:723)
  at android.view.Choreographer.doFrame(Choreographer.java:658)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
  at android.os.Handler.handleCallback(Handler.java:789)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by spakanati123** [comment]
Unfortunately, i am not authorized to share our code sample  :(
With the sample apps i did not observe the issue(sample apps load simple textures)
I can brief about our implementation:
After login the app we show discovery page which shows movie posters, the implementation done using the hetero recycler view set to discovery fragment.
We are populating data horizontally and vertically.
As of now we have 11 vertical rows and each row have 15 posters so total of 265 posters(bitmap set to ImageView) will loaded when we scroll completely.

logs:
https://drive.google.com/open?id=1Y9tNbjZGRLDRDArtfgqxwlepD7NfSWZM
https://drive.google.com/open?id=1pG_o0O9gwR49q9lZIdcoRz60he7A89li

When i select back key to go oculus home and press back to come back app ->  i can see the black screen and after while ANR dialog,
Kill app from recent windows and launch again -> again black screen and then ANR dialog.
in the attached logs please refer package name:  com.att.android.vr

**Comment by liaxim** [comment]
@spakanati123 Are you creating all of your GVRViewSceneObjects from the GVRMain.onInit method? Can send me the /data/anr/traces.txt file from the phone? It shows complete thread dump so I could see what on the rendering thread deadlocks the Android thread.

Can you build the framework yourself? Try removing the "synchronized (mLock)" from GVRViewSO.onNewParentObject and GVRViewSO.onRemoveParentObject.

**Comment by spakanati123** [comment]
@liaxim i am not adding all my scene objects in GVRMain.init.
Initially adding only login scene object and once login success removing the loginSceneObject and then adding the SplashScreenObject.
Once splash animation over i receive a callback, in the callback removing splashSceneObject and adding Discovery sceneObject.
