### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by aagocs** [Samsung/GearVRf#557]
Hello,

I can't get the demo apps working, in Android Studio 2.1.1. I followed the set up guide http://www.gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start.

Both source and binary has the same problem:
FindClass( com/oculus/vrapi/loader/AppLoader ) failed

Tried the static linked demo too (I read the README file)

E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.gearvrf.video, PID: 20408
                                                   java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-jsr223_e817e812ced964b81b982f49647807c1df258640-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-js_f2d65e1babe6e43a619b3df188a46d4f635796e9-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-jnlua-android_0ffa11933b86813a67faa5f3c2a99a1e4828a4e8-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-jline-android_dcd32127db6f041ebbb76492b0f4fa4f488af1c2-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-gvrf_exported_af19f37d1953d2296ada77b36580476514846e5c-classes.dex", dex file "/data/data/org.gearvrf.video/files/instant-run/dex/slice-gson-2.2.4_90b2d3e98b14002c8646d42c31c1cd16151f6997-classes.dex"],nativeLibraryDirectories=[/data/app/org.gearvrf.video-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgvrf.so"
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                       at java.lang.System.loadLibrary(System.java:1076)
                                                       at org.gearvrf.GVRActivityNative.<clinit>(GVRActivityNative.java:25)
                                                       at org.gearvrf.GVRActivity.onCreate(GVRActivity.java:85)
                                                       at org.gearvrf.video.VideoActivity.onCreate(VideoActivity.java:45)
                                                       at android.app.Activity.performCreate(Activity.java:6876)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Any idea what I'm doing wrong?

**Comment by aagocs** [comment]
Solved the first one, but I can't get to *.so files included as it seems. I tried to add it with build.gradle, packed as jar, and plain. Nothing helps.

**Comment by jason2kim** [comment]
From you log file, it says “couldn't find "libgvrf.so"”. 
Just to make sure, do you see  libgvrf.so file from your local folder: gvr-video-staticlib\gvrvideo\libs\lib\armeabi-v7a\

**Comment by jason2kim** [comment]
if you see libgvrf.so that you probably downloaded from releases/tag/3.0,
another thing to do is zip the lib folder and rename to lib.jar as described in README step 4.

**Comment by aagocs** [comment]
I got it work, thank you for your time

**Comment by Malikkhoja** [comment]
Hi @aagocs @jason2kim,

I am facing the same issue with the libgvrf.so. It says UnsatisfiedLinkError dlopen failed: cannot locate symbol "ovr_DisplaySystemActivityError".

Can you please help?

**Comment by liaxim** [comment]
@Malikkhoja Which version of the framework are you using? Are you trying to run one of our demos? ovr_DisplaySystemActivityError is a symbol from the Oculus Mobile SDK 0.6.2. There is no such in 1.0.4 - the one we currently use.
