### ISSUE TITLE
 Unable to start activity 

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#850]
Hello,
I tried to update to the current GearVRf Version, since then I can not start my app or any example app. I always get an error like that: 

FATAL EXCEPTION: main Process: com.my.app.mini.saklsdakl, PID: 24528
	java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app.mini.saklsdakl/org.gearvrf.gvr360Photo.Minimal360PhotoActivity}: java.lang.IllegalStateException: Fatal error: no backend available
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
		at android.app.ActivityThread.access$1100(ActivityThread.java:222)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
		at android.os.Handler.dispatchMessage(Handler.java:102)
		at android.os.Looper.loop(Looper.java:158)
		at android.app.ActivityThread.main(ActivityThread.java:7229)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
	 Caused by: java.lang.IllegalStateException: Fatal error: no backend available
		at org.gearvrf.GVRActivity.onCreate(GVRActivity.java:100)
		at org.gearvrf.gvr360Photo.Minimal360PhotoActivity.onCreate(Minimal360PhotoActivity.java:28)
		at android.app.Activity.performCreate(Activity.java:6876)
		at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
		at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
		at android.os.Handler.dispatchMessage(Handler.java:102) 
		at android.os.Looper.loop(Looper.java:158) 
		at android.app.ActivityThread.main(ActivityThread.java:7229) 
		at java.lang.reflect.Method.invoke(Native Method) 
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

Furthermore, seems to be something wrong with the examples, I can not open them in Android Studio anymore and compile them it's seems that they don't find the framework dependency. Is this just an error on my installation or does anyone else has those problems?

Thank you

**Comment by liaxim** [comment]
You need to add a new dependency to your build.gradle file. When you build the framework yourself there is a new aar artifact we create. The aar is GearVRf//GVRf/Framework/backend_oculus/build/outputs/aar/backend_oculus-debug.aar.

Opening the samples would just work as long as you have cloned both the framework and demos repository in the same directory. If there are in the same folder then building the framework would copy all dependencies to GearVRf-Demos/gearvrf-libs/. Please check the contents of the GearVRf-Demos/gearvrf-libs/ folder.

**Comment by liaxim** [comment]
Added an entry to https://github.com/Samsung/GearVRf/wiki/Build-Tips about what artifacts the build produces.

**Comment by leoncvlt** [comment]
I have got an automated setup which uses `gradlew` to install my application, however after adding `compile(name: 'backend_oculus-debug', ext: 'aar')` to my dependencies list, `gradlew install` build fails with the exception:

```
Execution failed for task ':app:transformClassesWithDexForShowreelDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/oculus/systemutils/BuildConfig;
```

**Comment by QKnows** [comment]
Thanks @liaxim - adding the aar's did the trick. I added the projects before, seems that this isn't working anymore.
One hint - the second aar file: backend_oculus-debug.aar is called backend-debug.aar 

gradle script: rename('backend_oculus-debug.aar', 'backend-debug.aar')

My issue is solved, the ticket can be closed depending on @leoncvlt

**Comment by liaxim** [comment]
@leoncvlt Most likely you still have VrApi.jar and SystemUtils.jar under the framework module (GearVRf/GVRf/Framework/framework/src/main/libs/). Please remove them from there, clean and build.

**Comment by leoncvlt** [comment]
@liaxim That did the trick, thanks.
