### ISSUE TITLE
NPE in gvr-3dcursor

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#978]
I think this happens after https://github.com/Samsung/GearVRf/pull/936, "New features in 3DCursor"

```
12-08 08:24:38.007  4825  4855 E AndroidRuntime: FATAL EXCEPTION: GVRGazeEventHandlerThread
12-08 08:24:38.007  4825  4855 E AndroidRuntime: Process: org.gearvrf.io.cursor, PID: 4825
12-08 08:24:38.007  4825  4855 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.gearvrf.GVRSceneObject.getName()' on a null object reference
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at org.gearvrf.io.cursor.CursorMain$5.onEvent(CursorMain.java:573)
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at org.gearvrf.io.cursor3d.Cursor.dispatchCursorEvent(Cursor.java:683)
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at org.gearvrf.io.cursor3d.Cursor.handleControllerEvent(Cursor.java:733)
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at org.gearvrf.io.cursor3d.ObjectCursor$1.onEvent(ObjectCursor.java:127)
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at org.gearvrf.GVRCursorController.update(GVRCursorController.java:620)
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at org.gearvrf.GVRCursorController.setPosition(GVRCursorController.java:423)
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at org.gearvrf.io.GVRGazeCursorController.access$101(GVRGazeCursorController.java:30)
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at org.gearvrf.io.GVRGazeCursorController$EventHandlerThread$1.handleMessage(GVRGazeCursorController.java:249)
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-08 08:24:38.007  4825  4855 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
--
```

**Comment by liaxim** [comment]
@parthmehta209 Could you please check it out? In developer mode I tried to move the cursor along the z axis on a Note5.
